sudo: true
language: node_js
node_js:
- 8.1.3
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
- unset CI
- yarn build
deploy:
  provider: s3
  access_key_id: $DEV_ACCESS_KEY_ID
  secret_access_key:
    secure: $DEV_SECRET_ACCESS_KEY
  bucket: dev-ehr.life.co
  skip_cleanup: true
  acl: public_read
  on:
    repo: LifeCo/lifeco-emr-web
    branch: develop
  local_dir: build
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"