sudo: true
language: node_js
node_js:
- 7.10.0
cache:
  yarn: true
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: s3
  access_key_id: AKIAJCZ6EJKGQ3A6J4LQ
  secret_access_key:
    secure: eph5vxAFZcLBnypa/56+5Nlix/FG+OO5dE0P4ynWosDVCd/N8tB6dw6yYoZ8H3Mm1LNkR6U9qgXoR6vPeyutipnzvZLurNnLDBbZUNy0Wm3TMRjY+qIf8CQmM3yhCJvu4F0d15VQKVN8rcs3a6TkgAQ2170+iydfJ8t+VDIFzMEqOM9xeXY1ufcHeoeF7CmYJTDtb4GWuFg9PuhktKhN58NdMceQpdos3VqYK0DHhzmceH64/GTFAFZvEzyDCncCFrllH4R0dXdLlq+RFjdF+E/sf7AgNDtogIs9rkOb3kOVXTby3sS8zJcPFmJpNlW4NzVbS14n8ymnOC6NJAMhh6xmzGGXNSK0Jyea5iA4Jcg4lVYoKMBIbrKP4oTinx4aIX3Jocgzw9OdKemK4I52LZJ+1qZqpI9KkA/1ercrovAaHnUSw4Ah0CLk8H5yVTdIbSt4zlJnjwigJF43mxk6W73msn3UXsGa2iwt8KsYrUDTN2wYk/HdxNTEjry8Y24586Cpj53j39Viu5C7zAqh4PDTi1yTYDzW5O7kzsVNbHaKC/67q8EUAOFXejOuneBRvpj3CL23UdINCvzAsT6m0xmamyfTdT+wRnEWCREC46Q2jUVoV3t7z1HYd7ROcifitCDRJ1qtpocCCRkc5E8KLh42xlt06ShYAv+ASJDf/5Q=
  bucket: dev-ehr.life.co
  acl: ''
  on:
    repo: LifeCo/lifeco-emr-web
    branch: chore/add-CI-CD
